/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Debug disabled */
#define ENABLE_DEBUG 0

/* Dump enabled */
/* #undef ENABLE_DUMP */

/* Buffer Dump disabled */
#define ENABLE_DUMPBUFF 0

/* Debug enabled */
/* #undef ENABLE_EFENCE */

/* verbosity enabled */
/* #undef ENABLE_VERBOSE */

/* Define default directory for Fenice A/V resources */
#define FENICE_AVROOT_DIR_DEFAULT /srv/fenice/avroot

/* Define default directory string for Fenice A/V resources */
#define FENICE_AVROOT_DIR_DEFAULT_STR "/srv/fenice/avroot"

/* Define default directory for Fenice configuration */
#define FENICE_CONF_DIR_DEFAULT /etc

/* Define default file for Fenice configuration */
#define FENICE_CONF_FILE_DEFAULT fenice.conf

/* Define absolute path string for Fenice configuration file */
#define FENICE_CONF_PATH_DEFAULT_STR "/etc/fenice.conf"

/* Define default file for Fenice logger */
#define FENICE_LOG_FILE_DEFAULT /mnt/mtd/Log/rtsp.log

/* Define default string for Fenice log file */
#define FENICE_LOG_FILE_DEFAULT_STR "/mnt/mtd/Log/rtsp.log"

/* Define max number of RTSP incoming sessions for Fenice */
#define FENICE_MAX_SESSION_DEFAULT 100

/* Define default RTSP listening port */
#define FENICE_RTSP_PORT_DEFAULT 554

/* Define if this is a development (subversion) tree */
/* #undef FENICE_SVN */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `getwd' function. */
#define HAVE_GETWD 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the `socket' function. */
#define HAVE_SOCKET 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcspn' function. */
#define HAVE_STRCSPN 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define to 1 if the system has the type `struct sockaddr_storage'. */
#define HAVE_STRUCT_SOCKADDR_STORAGE 1

/* Define to 1 if you have the <syslog.h> header file. */
#define HAVE_SYSLOG_H 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `uname' function. */
#define HAVE_UNAME 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/*for debugging print out,yanf*/
#ifdef RTSP_DEBUG
#define DEBUG_PRINTF(x) printf(x)
#define DEBUG_ERROR_STR     "@@@@@@@#######"
#define DEBUG_INFO_STR       "<><><><><><>"
#define DEBUG_INBUFFER_LINE_STR  "++++++++++++++++++++++++++++++ received data  ++++++++++++++++++++++++++++++\n"
#define DEBUG_OUTBUFFER_LINE_STR  "------------------------------ send data ------------------------------\n"

#define DEBUG_PRINT_ERROR(x)   \
    DEBUG_PRINTF(DEBUG_ERROR_STR);\
    DEBUG_PRINTF(x);    \
    DEBUG_PRINTF(DEBUG_ERROR_STR);   \
    DEBUG_PRINTF("\n");    

#define DEBUG_PRINT_INFO(x)   \
    DEBUG_PRINTF(DEBUG_INFO_STR);\
    DEBUG_PRINTF(x);    \
    DEBUG_PRINTF(DEBUG_INFO_STR);   \
    DEBUG_PRINTF("\n");        

#define DEBUG_PRINT_INBUFFER(x)  \
    DEBUG_PRINTF(DEBUG_INBUFFER_LINE_STR);\
    DEBUG_PRINTF(x);\
    DEBUG_PRINTF(DEBUG_INBUFFER_LINE_STR);
    
#define DEBUG_PRINT_OUTBUFFER(x)  \
    DEBUG_PRINTF(DEBUG_OUTBUFFER_LINE_STR);\
    DEBUG_PRINTF(x);\
    DEBUG_PRINTF(DEBUG_OUTBUFFER_LINE_STR);
    
#else   
#define DEBUG_PRINTF(x) 
#define DEBUG_ERROR_STR     ""
#define DEBUG_INFO_STR       ""
#define DEBUG_INBUFFER_LINE_STR  ""
#define DEBUG_OUTBUFFER_LINE_STR  ""
#define DEBUG_PRINT_ERROR(x)     

#define DEBUG_PRINT_INFO(x)        

#define DEBUG_PRINT_INBUFFER(x)  
    
#define DEBUG_PRINT_OUTBUFFER(x)  

#endif



/* Name of package */
#define PACKAGE "fenice"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "fenice"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "fenice 1.11"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "fenice"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.11"

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "1.11"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
