CROSS = arm-uclinux-elf-

CPP = $(CROSS)g++
CC  = $(CROSS)gcc
LD  = $(CROSS)ld
AR  = $(CROSS)ar

CFLAGS = -D_REENTRANT -DLINUX -Wall -O2 -I ../include -I ../
LFLAGS = -Wl,-elf2flt
LDFLAGS = -Wl,-elf2flt
AFLAGS	+= -rcu

LIBSCHEDULE = schedule.a
OBJS  =  schedule_add.o\
         schedule_do.o\
         schedule_init.o\
         schedule_remove.o\
         schedule_resume.o\
         schedule_start.o\
         schedule_stop.o

SOURCE = schedule_add.c\
         schedule_do.c\
         schedule_init.c\
         schedule_remove.c\
         schedule_resume.c\
         schedule_start.c\
         schedule_stop.c
         
all:$(LIBSCHEDULE)

$(LIBSCHEDULE):$(OBJS)
	$(AR) $(AFLAGS) $@ $^
	
.c.o:
	$(CC) -c $(CFLAGS) $<	-o $@
clean:
	rm -f *.o *.lo   *.a 