CROSS = arm-uclinux-elf-

CPP = $(CROSS)g++
CC  = $(CROSS)gcc
LD  = $(CROSS)ld
AR  = $(CROSS)ar

CFLAGS = -D_REENTRANT -DLINUX -Wall -O2 -I ../include -I ../
LFLAGS = -Wl,-elf2flt
LDFLAGS = -Wl,-elf2flt
AFLAGS	+= -rcu

LIMMULTICAST = multicast.a
OBJS  = is_valid_multicast_address.o

SOURCE = is_valid_multicast_address.c

all:$(LIMMULTICAST)

$(LIMMULTICAST):$(OBJS)
	$(AR) $(AFLAGS) $@ $^
	
.c.o:
	$(CC) -c $(CFLAGS) $<	-o $@
clean:
	rm -f *.o *.lo   *.a 
