CROSS = arm-uclinux-elf-

CPP = $(CROSS)g++
CC  = $(CROSS)gcc
LD  = $(CROSS)ld
AR  = $(CROSS)ar

CFLAGS = -D_REENTRANT -DLINUX -Wall -O2 -I ../include -I ../
LFLAGS = -Wl,-elf2flt
LDFLAGS = -Wl,-elf2flt
AFLAGS	+= -rcu

LIBEVENTLOOP = eventloop.a

OBJS  = add_client.o\
        eventloop.o\
        rtsp_server.o\
        schedule_connections.o

SOURCE = add_client.c\
        eventloop.c\
        rtsp_server.c\
        schedule_connections.c

all:$(LIBEVENTLOOP)

$(LIBEVENTLOOP):$(OBJS)
	$(AR) $(AFLAGS) $@ $^
	

.c.o:
	$(CC) -c $(CFLAGS) $<	-o $@
clean:
	rm -f *.o    *.a 